[package]
name = "roxido"
version = "0.2.0"
authors = ["David B. Dahl <dahl@stat.byu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libR-sys = "0.2.1"
rand_pcg = "0.3.0"
