[package]
name = 'caviarpd'
version = '0.1.0'
edition = '2018'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = "0.2"
rand = "0.8.3"
crossbeam = "0.8.0"
num_cpus = "1.13.0"
dahl-salso = "0.5.6"
epa = { path = "epa" }

